///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "9C110335-4A6D-47BD-B445-100EBD0E565B"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (Proof Tree Interpreter)"
#define COCLASS_UUID "B6F4DE94-6D0A-4A71-834A-23EEF2D5EC9A"
#define COCLASS_NAME "MGA Interpreter CoClass (Proof Tree Interpreter)"
#define COCLASS_PROGID "MGA.Interpreter.Proof Tree Interpreter"

#define COCLASS_UUID_EXPLODED1  0xb6f4de94
#define COCLASS_UUID_EXPLODED2   0x6d0a
#define COCLASS_UUID_EXPLODED3   0x4a71
#define COCLASS_UUID_EXPLODED4   0x83
#define COCLASS_UUID_EXPLODED5   0x4a
#define COCLASS_UUID_EXPLODED6   0x23
#define COCLASS_UUID_EXPLODED7   0xee
#define COCLASS_UUID_EXPLODED8   0xf2
#define COCLASS_UUID_EXPLODED9   0xd5
#define COCLASS_UUID_EXPLODED10  0xec
#define COCLASS_UUID_EXPLODED11  0x9a


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME _T("Proof Tree Interpreter")


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT _T("Proof Tree Interpreter")

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS _T("ProofTree")


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
